# Generated by Django 4.2.5 on 2023-09-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190904_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=10)),
                ('clients_mob', models.IntegerField(max_length=10, null=True)),
                ('clients_des', models.CharField(max_length=50, null=True)),
                ('client_BT', models.DateTimeField(null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloca_time', models.DateTimeField(null=True)),
                ('client_BT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clients')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
