# Generated by Django 4.2.5 on 2023-09-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_clients_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='count',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialist',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
