# Generated by Django 4.2.5 on 2023-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_allocation_count_employee_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='client_BT',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='emp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
