# Generated by Django 4.2.5 on 2023-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_allocation_client_bt_alter_allocation_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='count',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
