# Generated by Django 4.2.5 on 2024-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_id_alter_bookingsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=10)),
                ('booking_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='doc',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
