# Generated by Django 4.2.5 on 2024-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_mydoc_booking_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doc',
        ),
    ]
