# Generated by Django 4.2.5 on 2024-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doc',
            field=models.CharField(default='ajay', max_length=10),
        ),
    ]
