# Generated by Django 4.2.5 on 2024-03-24 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoc',
            name='created_att',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
